### PR TITLE
fix: support comments in multiline input

### LINKED ISSUE #12: Regression: Multiline support breaks .env files with quotes in comments
Hello there,

First thanks for keeping this crate alive.
I just tried to update to the latest version, but it broke my environment.
It looks like the new multiline support also checks within comments, and that breaks everything.

It is very simple to reproduce this by modifying `dotenv/tests/common/mod.rs` to this:
```rust
pub fn make_test_dotenv() -> io::Result<TempDir> {
    tempdir_with_dotenv(
        r#"
        # Start of .env file
        # Comment line with single ' quote
        # Comment line with double " quote
        TESTKEY=test_val
        # End of .env file
        "#
    )
}
```

That will create a multiline .env file to test with. And it will break.
When  you remove the two lines having a double and single quote it will run again.

I didn't had time to look into this my self, but maybe @hoijui or @allan2 knows a quick fix for this :).

For now i will stick with the previous version of this crate.

### PR DESCRIPTION
**Pull request by domodwyer**
Support parsing lines that contain comments & quotes.

Previously this input:

```
# Start of .env file
# Comment line with single ' quote
# Comment line with double " quote
 # Comment line with double " quote and starts with a space
TESTKEY=test_val # A '" comment
# End of .env file
```

Would fail the regression test (`test_issue_12`):

```
running 1 test
test test_issue_12 ... FAILED

failures:

---- test_issue_12 stdout ----
thread 'test_issue_12' panicked at 'should succeed: LineParse("# Comment line with single ' quote\n# Comment line with double \" quote\n # Comment line with double \" quote and starts with a space\nTESTKEY=test_val # A '\" comment\n# End of .env file\n", 181)', dotenv/tests/test-multiline-comment.rs:21:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1805:5
   3: core::result::Result<T,E>::expect
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1055:23
   4: test_multiline_comment::test_issue_12
             at /Users/dom/Documents/rust/dotenvy/dotenv/tests/test-multiline-comment.rs:21:5
   5: test_multiline_comment::test_issue_12::{{closure}}
             at /Users/dom/Documents/rust/dotenvy/dotenv/tests/test-multiline-comment.rs:8:1
   6: core::ops::function::FnOnce::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

After this commit, the env var is set as expected (`test_val`).

Fixes #12. 

---

* fix: support comments in multiline input (0bcc818)

      Fixes the line parser to respect comments when evaluating quote state.

      Fixes allan2/dotenvy#12.

### CODE REVIEW

File: dotenv/src/iter.rs [hunk 1]
```diff
@@ -38,39 +38,45 @@ struct QuotedLines<B> {
...
+                _ => ParseState::WeakOpen,
             },
-            QuoteState::WeakOpenEscape => QuoteState::WeakOpen,
-            QuoteState::StrongOpen => match c {
-                '\\' => QuoteState::StrongOpenEscape,
-                '\'' => QuoteState::Complete,
-                _ => QuoteState::StrongOpen,
+            ParseState::WeakOpenEscape => ParseState::WeakOpen,
+            ParseState::StrongOpen => match c {
+                '#' => return ParseState::Comment,
```
Comment (LeoniePhiline) [inline dotenv/src/iter.rs:72]: Here a regression is introduced: 
This line makes `KEY='ABC#DEF'` get truncated as `KEY='ABC`
